# Generated by Django 5.1.3 on 2024-11-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.BigIntegerField()),
                ('discountPercentage', models.FloatField()),
                ('stock', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('thumbnail', models.URLField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
